version: '3'
services:
  react-app:
    container_name: groove-grove-react
    build:
      context: ./app
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"
    depends_on:
      - express-server
    networks:
      - groove-grove
    environment:
      - REACT_APP_FIREBASE_API_KEY=AIzaSyCuS0hlDdXNoJnTcrumwkVcoZC6CNpczJc
      - REACT_APP_FIREBASE_AUTH_DOMAIN=groove-grove-3d74c.firebaseapp.com
      - REACT_APP_FIREBASE_PROJECT_ID=groove-grove-3d74c
      - REACT_APP_FIREBASE_STORAGE_BUCKET=groove-grove-3d74c.appspot.com
      - REACT_APP_FIREBASE_MESSAGING_SENDER_ID=478223878731
      - REACT_APP_FIREBASE_APP_ID=1:478223878731:web:35de13c763686fafe51bce
      - REACT_APP_FIREBASE_MEASUREMENT_ID=G-MLY84MMRYT

  express-server:
    container_name: groove-grove-express
    image: mongo-express:latest
    ports:
      - "5000:8081"
    depends_on:
      - mongodb
    networks:
      - groove-grove
    environment:
      - ME_CONFIG_MONGODB_SERVER=groove-grove-mongodb

  mongodb:
    container_name: groove-grove-mongodb
    image: mongo:latest
    networks:
      - groove-grove
    volumes:
      - mongodb-data:/data/db

networks:
  groove-grove:
    external: true

volumes:
  mongodb-data:
    external: false